# -*- coding: utf-8 -*-
"""Scrapping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_GAFnFbU_ZpDwdTr3io4prDfviWFb02
"""

!pip install google-play-scraper

# Mengimpor pustaka google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews, Sort, reviews_all
import requests
import pandas as pd

import nltk  # Import pustaka NLTK (Natural Language Toolkit).
nltk.download('punkt')  # Mengunduh dataset yang diperlukan untuk tokenisasi teks.
nltk.download('punkt_tab')

# Mengambil semua ulasan dari aplikasi dengan ID 'com.grabtaxi.passenger' di Google Play Store.

grab_reviews = reviews(
    'com.grabtaxi.passenger',  # ID aplikasi Grab
    lang='id',                 # Bahasa: Indonesia
    country='id',              # Negara: Indonesia
    sort=Sort.MOST_RELEVANT,   # Mengurutkan dari yang paling relevan
    count=12000                 # hanya mengambil 40000 ulasan
)


# mengambil hanya bagian ulasan (content dan score)
df = pd.DataFrame(grab_reviews[0])[['content', 'score']]
#Menyimpan ulasan ke csv
df.to_csv("grab_reviews.csv", index=False, encoding='utf-8-sig')